language: python

git:
  submodules: false

branches:
  only:
  - sources

before_install:
- openssl aes-256-cbc -K $encrypted_bf42b6e438ff_key -iv $encrypted_bf42b6e438ff_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key

install:
- pip install -r requirements.txt
- git submodule update --init
- cd themes && git submodule init Flex && cd -
- cd themes && git submodule update && cd -

script:
- make publish github

notification:
    email:
        on_failure: always
